#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)
echo "${bold}root mode${normal}"
service hhvm-tophost stop
service nginx restart
service php-fpm start
echo "${bold}restart of nginx and php-fm succeed${normal}"
chkconfig php-fpm on
chkconfig hhvm-tophost off
service spawn-fcgi restart
echo "${bold}restart spawn-fcgi succeed${normal}"
yum -y install postfix
service postfix restart
chkconfig postfix on
echo "${bold}installation, restart and enable services for mdbill and email succeed${normal}"

